my :
  message : this is hello message.
spring:
  datasource:
    url: jdbc:h2:file:./data/board;AUTO_SERVER=TRUE
    username : sa
    password :
    driver-class-name : org.h2.Driver
h2:
  console:
    enabled:true
  path: /h2-console
#logging:
# level:
#   org.springframework.web: DEBUG
